### ISSUE TITLE
async def handler(event):

### ISSUE THREAD

**Issue by rumputliar** [soxoj/maigret-tg-bot#2]
Hello, i got this error when execute the script, by the way i'm using python 3.8
File "D:\Scripts Py\Telegram BOT\maigret-tg-bot\bot.py", line 129
    async def handler(event):
          ^
SyntaxError: invalid syntax

**Comment by soxoj** [comment]
Hello, are you sure that you are using 3.8?
Please, do the following and copy the console output:
```sh
$ python3 --version
$ python3 bot.py
```

**Comment by soxoj** [comment]
Fixed in e1d25ab
