### ISSUE TITLE
SyntaxError: '(' was never closed

### ISSUE THREAD

**Issue by SkrudjReal** [soxoj/maigret-tg-bot#3]
[gooder@GOD maigret-tg-bot]$ python bot.py 
  File "/home/gooder/Desktop/54/maigret-tg-bot/bot.py", line 127
    @client.on(events.NewMessage()
              ^
SyntaxError: '(' was never closed

Do

127 line:

`        @client.on(events.NewMessage())`

**Comment by soxoj** [comment]
Hello, are you sure that you are using 3.8?
Please, do the following and copy the console output:

```
$ python3 --version
$ python3 bot.py
```

**Comment by soxoj** [comment]
Hi, thank you, I'll fix it.

**Comment by soxoj** [comment]
Fixed in e1d25ab
